name: Build Test
on:
  push:
    branches-ignore:
      #- main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: bun

      - name: setup-bun
        uses: oven-sh/setup-bun@v1

      - name: bun-install
        run: bun install

      - name: app-build
        run: bun run build